name: extend-awards
on:
  pull_request_target:
    types: [closed]
    branches:
      - master
permissions:
  pull-requests: write
  contents: write
  issues: read
jobs:
  if_merged:
    if: |
      github.event_name == 'pull_request_target' &&
      github.event.action == 'closed' &&
      github.event.pull_request.merged == true &&
      github.event.pull_request.head.ref != 'extend-awards/patch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install requests
      - name: Run extend-awards script
        run: python extend-awards.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Fetch and rebase branch
        run: |
          git fetch origin extend-awards/patch || true
          git rebase origin/extend-awards/patch || true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: awards.csv
          branch: extend-awards/patch
          commit-message: Extending awards.csv
          title: Extending awards.csv
          body: A PR was merged that solves an issue and awards.csv should be extended.