# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: 'Next.js Bundle Analysis'

on:
  pull_request:
  push:
    branches:
      - master # change this if your default branch is named differently
  workflow_dispatch:

defaults:
  run:
    # change this if your nextjs app does not live at the root of the repo
    working-directory: ./

permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats
  pull-requests: write # for comments

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Restore next build
        uses: actions/cache@v3
        id: restore-build-cache
        env:
          cache-name: cache-next-build
        with:
          path: .next/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Create dotenv file
        run: |
          touch .env
          cat .env.development >> .env
          cat .env.production >> .env
          echo "VAPID_MAILTO=mailto:cicd@stacker.news" >> .env
          echo "NEXT_PUBLIC_VAPID_PUBKEY=BPxWyxu_wyLJKvK8YQIOz9Bu7lyck6PJVZE9DcZKuxMzii_AcS6J43N8xaed6Q4uBmeMuUvAHE6UQRGIJY1CCMo" >> .env
          echo "VAPID_PRIVKEY=mqF8ZYR8DucADCoyux17QCy8T_kFocnfDWEOndPW-WE" >> .env
          echo "Environment:"
          cat .env

      - name: Build next.js app
        # change this if your site requires a custom build command
        run: ./node_modules/.bin/next build

      # Here's the first place where next-bundle-analysis' own script is used
      # This step pulls the raw bundle stats for the current bundle
      - name: Analyze bundle
        run: npx -p nextjs-bundle-analysis report

      - name: Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: bundle
          path: .next/analyze/__bundle_analysis.json

      # - name: Download base branch bundle stats
      #   uses: dawidd6/action-download-artifact@v2
      #   if: success() && github.event.number
      #   with:
      #     workflow: nextjs_bundle_analysis.yml
      #     branch: ${{ github.event.pull_request.base.ref }}
      #     path: .next/analyze/base

      # - name: Compare with base branch bundle
      #   if: success() && github.event.number
      #   run: ls -laR .next/analyze/base && npx -p nextjs-bundle-analysis compare

      # - name: Get Comment Body
      #   id: get-comment-body
      #   if: success() && github.event.number
      #   run: |
      #     echo "body<<EOF" >> $GITHUB_OUTPUT
      #     echo "$(cat .next/analyze/__bundle_analysis_comment.txt)" >> $GITHUB_OUTPUT
      #     echo EOF >> $GITHUB_OUTPUT

      # - name: Find Comment
      #   uses: peter-evans/find-comment@v2
      #   if: success() && github.event.number
      #   id: fc
      #   with:
      #     issue-number: ${{ github.event.number }}
      #     body-includes: '<!-- __NEXTJS_BUNDLE -->'

      # - name: Create Comment
      #   uses: peter-evans/create-or-update-comment@v2
      #   if: success() && github.event.number && steps.fc.outputs.comment-id == 0
      #   with:
      #     issue-number: ${{ github.event.number }}
      #     body: ${{ steps.get-comment-body.outputs.body }}

      # - name: Update Comment
      #   uses: peter-evans/create-or-update-comment@v2
      #   if: success() && github.event.number && steps.fc.outputs.comment-id != 0
      #   with:
      #     issue-number: ${{ github.event.number }}
      #     body: ${{ steps.get-comment-body.outputs.body }}
      #     comment-id: ${{ steps.fc.outputs.comment-id }}
      #     edit-mode: replace
